name: photo_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  dio: ^4.0.0
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  intl_utils: ^2.3.0
  json_serializable: ^4.1.3
  pull_to_refresh: ^2.0.0

dev_dependencies:
  bloc_test: ^8.0.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.0.0

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: vi
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
